name: Fetch Infisical Secrets
author: "Infisical"
description: "Fetch secrets from Infisical into your Github workflows"
branding:
  icon: "lock"
  color: "yellow"
inputs:
  method:
    description: "The authentication method to use"
    required: false
    default: "universal"
  client-id:
    description: "Machine Identity client ID"
    required: true
  client-secret:
    description: "Machine Identity secret key"
    required: true
  identity-id:
    description: "Machine Identity ID"
    required: false
  oidc-audience:
    description: "Custom aud claim for the signed Github ID token"
    required: false
  project-slug:
    description: "Source project slug"
    required: false
    default: project-github-actions
  env-slug:
    description: "Source environment slug"
    required: false
    default: master
  domain:
    description: "Infisical URL (defaults to https://eu.infisical.com )"
    required: false
    default: "https://eu.infisical.com"
  export-type:
    description: "If set to `env`, it will set the fetched secrets as environment variables for subsequent steps of a workflow. If set to `file`, it will export the secrets in a .env file in the defined file-output-path"
    required: false
    default: "env"
  file-output-path:
    description: "The path to save the file when export-type is set to `file`"
    required: false
    default: "/.env"
  secret-path:
    description: "Source path, example: `/my-secret-path`"
    required: true
  include-imports:
    description: "If set to `true`, it will include imported secrets"
    required: false
    default: true
  recursive:
    description: "If set to `true`, it will fetch all secrets from the specified base path and all of its subdirectories"
    required: false
    default: false
  retry-attempts:
    description: "Number of retry attempts for network requests"
    required: false
    default: 10
runs:
  using: "node20"
  main: "dist/index.js"
